apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector: { matchLabels: { app: flask } }
  template:
    metadata: { labels: { app: flask } }
    spec:
      containers:
      - name: flask
        image: ayansrivastava11/flask-app:latest 
        resources:
          requests: { cpu: "0.2", memory: "250Mi" }
          limits: { cpu: "0.5", memory: "500Mi" }
        ports: [{ containerPort: 5000 }]
        env:
        - name: MONGO_USER
          valueFrom: { secretKeyRef: { name: mongo-secret, key: username } }
        - name: MONGO_PASS
          valueFrom: { secretKeyRef: { name: mongo-secret, key: password } }
        - name: MONGO_HOST
          value: "mongodb-service" # K8s DNS name
